#!/usr/bin/env bash
# Compile every profile's GTK3/GTK4/Cinnamon/libadwaita CSS from the SCSS
# sources, using the standalone Dart Sass CLI (no Node/Bun/npm involved).
#
# Per profile: write a generated _profile.scss into each SCSS target directory,
# compile with `sass`, then rewrite every legacy Mint-Y hex/rgba literal in the
# compiled CSS to its profile colour via scripts/apply-remap.py (per
# src/scss/gtk-3.0/remap-manifest.scss's $legacy/$legacy-rgba maps). Static
# assets under src/cinnamon, src/metacity-1 and src/static are copied verbatim,
# with @@PLACEHOLDER@@ substitution for any `*.in` file. Port of build.ts —
# see that file's git history for the original TypeScript version.
#
# Usage: build.sh [DIST_DIR]   (default: dist)
set -euo pipefail

DIST="${1:-dist}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REMAP_MANIFEST="src/scss/gtk-3.0/remap-manifest.scss"
SCSS_DIRS=(src/scss/gtk-3.0 src/scss/gtk-4.0 src/scss/cinnamon src/scss/libadwaita)

# Prefer a system-installed `sass`; fall back to the vendored standalone
# binary `make deps` downloads (same one CI uses — see Makefile).
SASS="$(command -v sass || true)"
if [ -z "$SASS" ]; then
  SASS="$SCRIPT_DIR/.tools/dart-sass/sass"
fi
if [ ! -x "$SASS" ] && ! command -v "$SASS" >/dev/null 2>&1; then
  echo "build.sh: no 'sass' found on PATH and $SASS is not installed — run 'make deps'" >&2
  exit 1
fi

# Any _profile.scss / manifest / raw-CSS temp file that's mid-flight when a
# command fails under `set -e` — cleaned up unconditionally on exit so a
# compile failure never leaves generated cruft behind (build.ts guaranteed
# this with try/finally; a plain trailing `rm -f` in each function does not,
# since it's skipped when the preceding command in that function fails).
MANIFEST_CSS=""
RAW_TMP=""
cleanup() {
  local d
  for d in "${SCSS_DIRS[@]}"; do rm -f "$d/_profile.scss"; done
  if [ -n "$MANIFEST_CSS" ]; then rm -f "$MANIFEST_CSS"; fi
  if [ -n "$RAW_TMP" ]; then rm -f "$RAW_TMP"; fi
  return 0
}
trap cleanup EXIT

# Run sass, dropping any stderr paragraph containing "color value" — the
# known false positive that fires when ri() rounds a very dark bg to
# rgb(0,0,0) and Sass's own stringifier renders it as the keyword "black"
# during interpolation. The output is correct, valid CSS either way; this
# only silences the warning about it, same as the old JS API logger did.
run_sass() {
  "$SASS" "$@" 2> >(awk 'BEGIN{RS="";ORS="\n\n"} !/color value/' >&2)
}

# Read one flat top-level key from a profile yaml — shared with the Makefile's
# deactivate-if-active, which needs the exact same parsing to compare against
# the live gsettings theme name. Keeping one implementation means a case
# neither of us has hit yet (a quoted value, a trailing comment) can't make
# the two silently disagree.
field() {
  "$SCRIPT_DIR/scripts/yaml-field.sh" "$1" "$2"
}

write_profile_scss() {
  local dir="$1"
  cat > "$dir/_profile.scss" <<EOF
// Generated by build.sh — do not edit
\$accent:  $ACCENT;
\$bg:      $BG;
\$fg:      $FG;
\$error:   $ERROR;
\$warning: $WARNING;
\$success: $SUCCESS;
\$strong:  $STRONG;
EOF
}

# Compile remap-manifest.scss for the current profile and keep its resolved
# --m-<hex>/--m-rgba-<slug> custom properties around for apply-remap.py.
resolve_remap() {
  local dir; dir="$(dirname "$REMAP_MANIFEST")"
  write_profile_scss "$dir"
  MANIFEST_CSS="$(mktemp)"
  run_sass "$REMAP_MANIFEST" --style=expanded --no-source-map > "$MANIFEST_CSS"
  rm -f "$dir/_profile.scss"
}

# compile_scss ENTRY OUT [remap]
compile_scss() {
  local entry="$1" out="$2" remap="${3:-}"
  local dir; dir="$(dirname "$entry")"
  write_profile_scss "$dir"
  mkdir -p "$(dirname "$out")"
  if [ "$remap" = "remap" ]; then
    RAW_TMP="$(mktemp)"
    run_sass "$entry" --style=expanded --no-source-map > "$RAW_TMP"
    python3 "$SCRIPT_DIR/scripts/apply-remap.py" "$MANIFEST_CSS" "$RAW_TMP" "$out"
    rm -f "$RAW_TMP"
    RAW_TMP=""
  else
    run_sass "$entry" --style=expanded --no-source-map > "$out"
  fi
  rm -f "$dir/_profile.scss"
}

# process_assets SRC_DIR DEST_DIR [SKIP_SUFFIX]
# Copies SRC_DIR into DEST_DIR: files ending SKIP_SUFFIX are dropped, `*.in`
# files get @@PLACEHOLDER@@ substitution with the `.in` stripped, everything
# else is copied verbatim.
process_assets() {
  local src="$1" dest="$2" skip="${3:-}"
  mkdir -p "$dest"
  local rel
  while IFS= read -r -d '' path; do
    rel="${path#"$src"/}"
    if [ -n "$skip" ] && [[ "$rel" == *"$skip" ]]; then
      continue
    elif [[ "$rel" == *.in ]]; then
      mkdir -p "$(dirname "$dest/${rel%.in}")"
      sed \
        -e "s|@@THEME_NAME@@|$NAME|g" \
        -e "s|@@ACCENT@@|$ACCENT|g" \
        -e "s|@@BG@@|$BG|g" \
        -e "s|@@FG@@|$FG|g" \
        -e "s|@@FG_CINN@@|$FG|g" \
        -e "s|@@ERROR@@|$ERROR|g" \
        -e "s|@@ERROR_ALT@@|$ERROR|g" \
        -e "s|@@ERROR_DARK@@|$ERROR|g" \
        -e "s|@@WARNING@@|$WARNING|g" \
        -e "s|@@SUCCESS@@|$SUCCESS|g" \
        -e "s|@@SUCCESS_ALT@@|$SUCCESS|g" \
        -e "s|@@BG_DARK@@|$BG|g" \
        -e "s|@@BG_DARKER@@|$BG|g" \
        -e "s|@@CINN_BG@@|$BG|g" \
        "$path" > "$dest/${rel%.in}"
    else
      mkdir -p "$(dirname "$dest/$rel")"
      cp "$path" "$dest/$rel"
    fi
  done < <(find "$src" -type f -print0)
}

# The Themes applet shows each component's preview from a static thumbnail.png
# (gtk-3.0 = Applications, cinnamon = Desktop, metacity-1 = Window borders).
# Forked verbatim from Mint-Y these are grey, so recolour them to the profile:
# a duotone mapping shadows->$bg and highlights->$fg gives the monochrome
# amber-phosphor preview from the raw profile primitives. Needs ImageMagick
# `convert`; if absent, or if a specific recolour fails, the build still
# succeeds — a thumbnail is cosmetic, not worth aborting every remaining
# profile over (build.ts degraded the same way via try/catch).
recolor_thumbnails() {
  local out="$1"
  if ! command -v convert >/dev/null 2>&1; then
    echo "WARNING: ImageMagick 'convert' not found — preview thumbnails left grey" >&2
    return 0
  fi
  local rel
  for rel in gtk-3.0/thumbnail.png cinnamon/thumbnail.png metacity-1/thumbnail.png; do
    if [ -f "$out/$rel" ]; then
      convert "$out/$rel" +level-colors "$BG,$FG" "$out/$rel" \
        || echo "WARNING: failed to recolour $rel — left as-is" >&2
    fi
  done
  return 0
}

write_index_theme() {
  local out="$1"
  cat > "$out/index.theme" <<EOF
[Desktop Entry]
Type=X-GNOME-Metatheme
Name=$NAME
Comment=Amber Linux — $NAME (1980s amber-phosphorus desktop theme)
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=$NAME
MetacityTheme=$NAME
IconTheme=$NAME
CursorTheme=Bibata-Modern-Ice
ButtonLayout=close,minimize,maximize:
EOF
}

build_theme() {
  local profile="$1"
  NAME="$(field "$profile" name)"
  ACCENT="$(field "$profile" accent)"
  BG="$(field "$profile" bg)"
  FG="$(field "$profile" fg)"
  ERROR="$(field "$profile" error)"
  WARNING="$(field "$profile" warning)"
  SUCCESS="$(field "$profile" success)"
  STRONG="$(field "$profile" strong)"

  local out="$DIST/$NAME"
  echo "Building $NAME → $out"
  rm -rf "$out"

  resolve_remap

  compile_scss src/scss/gtk-3.0/main.scss "$out/gtk-3.0/gtk-dark.css" remap
  cp "$out/gtk-3.0/gtk-dark.css" "$out/gtk-3.0/gtk.css"

  compile_scss src/scss/gtk-4.0/main.scss "$out/gtk-4.0/gtk-dark.css" remap
  cp "$out/gtk-4.0/gtk-dark.css" "$out/gtk-4.0/gtk.css"

  compile_scss src/scss/cinnamon/main.scss "$out/cinnamon/cinnamon.css" remap
  process_assets src/cinnamon "$out/cinnamon" .css.in

  # Muffin/metacity window-border theme. The XML resolves its colours at runtime
  # via gtk:custom(named_color, …) and recolours the button icons with
  # colorize="…", both reading the active GTK theme's wm_* named colours — so it
  # tracks the profile automatically and ships verbatim.
  process_assets src/metacity-1 "$out/metacity-1"

  compile_scss src/scss/libadwaita/main-dark.scss "$out/libadwaita-1.5/defaults-dark.css" remap
  compile_scss src/scss/libadwaita/main-light.scss "$out/libadwaita-1.5/defaults-light.css" remap

  rm -f "$MANIFEST_CSS"
  MANIFEST_CSS=""

  write_index_theme "$out"
  cp -r src/static/. "$out/"
  recolor_thumbnails "$out"

  echo "Done: $NAME"
}

shopt -s nullglob
profiles=(profiles-yaml/*.yaml)
shopt -u nullglob
if [ ${#profiles[@]} -eq 0 ]; then
  echo "build.sh: no profiles found in profiles-yaml/" >&2
  exit 1
fi

for profile in "${profiles[@]}"; do
  build_theme "$profile"
done
